name: Pillarsofhealth
favicon: null
layout_spectrum: 0.5097813236061484
typography_spectrum: 0.3050679012667388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.38860094267874956
  lightness: 0.8921153172850609
  saturation: 0.5448835561983287
  rhythmicContrast: 0.7696925387717783
purpose: []
